#include <stdio.h>
#include <stdlib.h>

static void unexpected(const char* symbol)
{
    fprintf(stderr, "unexpected core dependency: %s\n", symbol);
    abort();
}

// These are link-visible only so unsupported branches fail with a named
// diagnostic. Any symbol reached by Fox/Fox gameplay must be imported or
// reclassified with explicit source-backed semantics before the source boundary closes.
#define ABORT_STUB(name) void name() { unexpected(#name); }

ABORT_STUB(HSD_LObjAddCurrent)
ABORT_STUB(HSD_LObjClearFlags)
ABORT_STUB(HSD_LObjRemoveAll)
ABORT_STUB(HSD_LObjSetCurrentAll)
ABORT_STUB(HSD_LObjSetFlags)
ABORT_STUB(HSD_LObjSetupInit)
ABORT_STUB(HSD_LObj_803668EC)
ABORT_STUB(ftCh_GrabUnk1_8015ADD0)
ABORT_STUB(ftCh_GrabUnk1_8015BC88)
ABORT_STUB(ftMh_MS_343_80151484)
ABORT_STUB(ftMh_MS_389_80151018)
ABORT_STUB(it_8028B08C)
ABORT_STUB(it_8028B618)
ABORT_STUB(it_8028B648)
ABORT_STUB(it_8028B6B0)
ABORT_STUB(it_8028B718)
ABORT_STUB(it_8028B780)
ABORT_STUB(it_8028B7E8)
ABORT_STUB(it_8028B850)
ABORT_STUB(lbRefract_80022998)
ABORT_STUB(lbRefract_80022BD0)

// Indexed branches retained by common fighter code but impossible for the
// current Fox-only kind domain.
ABORT_STUB(ftCh_Init_80156014)
ABORT_STUB(ftCl_Init_8014919C)
ABORT_STUB(ftCl_Init_80149318)
ABORT_STUB(ftDk_MS_349_800E06D8)
ABORT_STUB(ftGw_Attack11_Enter)
ABORT_STUB(ftGw_AttackAirN_DecideAction)
ABORT_STUB(ftGw_AttackLw3_Enter)
ABORT_STUB(ftGw_AttackS4_Enter)
ABORT_STUB(ftKb_SpecialNFx_800FDC00)
ABORT_STUB(ftKb_SpecialNFx_800FDC70)
ABORT_STUB(ftKb_SpecialNFx_800FDD14)
ABORT_STUB(ftKb_SpecialNFx_800FDD4C)
ABORT_STUB(ftKb_SpecialNFx_800FDDF4)
ABORT_STUB(ftKb_SpecialNFx_800FDEB4)
ABORT_STUB(ftKb_SpecialNSk_80105FF0)
ABORT_STUB(ftKb_SpecialNSk_80106020)
ABORT_STUB(ftKb_SpecialNSs_800FCC14)
ABORT_STUB(ftKb_SpecialNSs_800FCC6C)
ABORT_STUB(ftKb_SpecialNSs_800FCCBC)
ABORT_STUB(ftKb_SpecialNSs_800FCD04)
ABORT_STUB(ftKb_SpecialN_800F1CD8)
ABORT_STUB(ftKb_SpecialN_800F1F68)
ABORT_STUB(ftKb_SpecialN_800F5D04)
ABORT_STUB(ftLk_AttackAir_800EB3BC)
ABORT_STUB(ftLk_AttackAir_Enter)
ABORT_STUB(ftMh_MS_341_8014FE58)
ABORT_STUB(ftNs_AttackLw4_Enter)
ABORT_STUB(ftNs_AttackS4_Enter)
ABORT_STUB(ftYs_Init_8012B8A4)
ABORT_STUB(ftYs_Init_8012BAC0)
ABORT_STUB(ftYs_Init_8012BDA0)
ABORT_STUB(ftYs_Init_8012BE3C)
ABORT_STUB(ftYs_Init_8012BECC)
ABORT_STUB(ftYs_Shield_8012C600)
ABORT_STUB(ftYs_Shield_8012C914)
ABORT_STUB(ftYs_Shield_8012CC1C)

// Held/common items and non-Fox articles are disabled by the current match
// rules. These source branches remain loud if that domain assumption changes.
ABORT_STUB(ftCo_800CD82C)
ABORT_STUB(ftCo_800CDAB4)
ABORT_STUB(it_8028E774)
ABORT_STUB(it_8028E79C)
ABORT_STUB(it_8028E938)
ABORT_STUB(it_8028FE90)
ABORT_STUB(it_80291DAC)
ABORT_STUB(it_80291F14)
ABORT_STUB(it_80292EAC)
ABORT_STUB(it_80292EF8)
ABORT_STUB(it_80292F14)
ABORT_STUB(it_80293660)
ABORT_STUB(it_80293DCC)
ABORT_STUB(it_80293E34)
ABORT_STUB(it_80294364)
ABORT_STUB(it_80294430)
ABORT_STUB(it_80294E78)
ABORT_STUB(it_80294EB0)
ABORT_STUB(it_802950D4)
ABORT_STUB(it_8029A748)
ABORT_STUB(it_8029A89C)
ABORT_STUB(it_8029A8F4)
ABORT_STUB(it_8029D968)
ABORT_STUB(it_802D09D0)
ABORT_STUB(it_802E5EF4)
ABORT_STUB(it_802E5F8C)
ABORT_STUB(it_802EAAEC)
ABORT_STUB(it_802EADD8)
ABORT_STUB(it_802EAF28)

ABORT_STUB(grKongo_801D828C)
ABORT_STUB(grOldKongo_802105C8)

// The complete common MotionState table deliberately retains entries and
// kind-dispatch branches for fighters, held items, and stages outside the
// current Fox/FD/items-off boundary. Keep those links loud instead of silently
// changing a callback. No Fox/FD gameplay path may reach one of these.
ABORT_STUB(ftCo_CaptureCrazyHand_Anim)
ABORT_STUB(ftCo_CaptureCrazyHand_Coll)
ABORT_STUB(ftCo_CaptureCrazyHand_IASA)
ABORT_STUB(ftCo_CaptureCrazyHand_Phys)
ABORT_STUB(ftCo_CaptureDamageCrazyHand_Anim)
ABORT_STUB(ftCo_CaptureDamageCrazyHand_Coll)
ABORT_STUB(ftCo_CaptureDamageCrazyHand_IASA)
ABORT_STUB(ftCo_CaptureDamageCrazyHand_Phys)
ABORT_STUB(ftCo_CaptureKirbyYoshi_Anim)
ABORT_STUB(ftCo_CaptureKirbyYoshi_Coll)
ABORT_STUB(ftCo_CaptureKirbyYoshi_IASA)
ABORT_STUB(ftCo_CaptureKirbyYoshi_Phys)
ABORT_STUB(ftCo_CaptureLikelike_Anim)
ABORT_STUB(ftCo_CaptureLikelike_Coll)
ABORT_STUB(ftCo_CaptureLikelike_IASA)
ABORT_STUB(ftCo_CaptureLikelike_Phys)
ABORT_STUB(ftCo_CaptureWaitCrazyHand_Anim)
ABORT_STUB(ftCo_CaptureWaitCrazyHand_Coll)
ABORT_STUB(ftCo_CaptureWaitCrazyHand_IASA)
ABORT_STUB(ftCo_CaptureWaitCrazyHand_Phys)
ABORT_STUB(ftCo_KirbyYoshiEgg_Anim)
ABORT_STUB(ftCo_KirbyYoshiEgg_Coll)
ABORT_STUB(ftCo_KirbyYoshiEgg_IASA)
ABORT_STUB(ftCo_KirbyYoshiEgg_Phys)
ABORT_STUB(ftCo_LipstickSwing_Anim)
ABORT_STUB(ftCo_LipstickSwing_Coll)
ABORT_STUB(ftCo_LipstickSwing_IASA)
ABORT_STUB(ftCo_LipstickSwing_Phys)
ABORT_STUB(ftCo_StarRodSwing_Anim)
ABORT_STUB(ftCo_StarRodSwing_Coll)
ABORT_STUB(ftCo_StarRodSwing_IASA)
ABORT_STUB(ftCo_StarRodSwing_Phys)
ABORT_STUB(ftCo_ThrownCrazyHand_Anim)
ABORT_STUB(ftCo_ThrownCrazyHand_Coll)
ABORT_STUB(ftCo_ThrownCrazyHand_IASA)
ABORT_STUB(ftCo_ThrownCrazyHand_Phys)
ABORT_STUB(ftDk_MS_341_800DF980)
ABORT_STUB(ftGw_Attack100Start_Enter)
ABORT_STUB(ftKb_SpecialN_800EEEC4)
ABORT_STUB(ftKb_SpecialN_800F190C)
ABORT_STUB(ftKb_SpecialN_800F5874)
ABORT_STUB(ftKb_SpecialN_800F5954)
ABORT_STUB(ftKb_SpecialN_800F597C)
ABORT_STUB(ftKb_SpecialN_800F598C)
ABORT_STUB(ftKb_SpecialN_800F5A04)
ABORT_STUB(ftKb_SpecialN_800F5A38)
ABORT_STUB(ftKb_SpecialN_800F5A60)
ABORT_STUB(ftKb_SpecialN_800F5A70)
ABORT_STUB(ftKb_SpecialN_800F5A98)
ABORT_STUB(ftKb_SpecialN_800F5AC0)
ABORT_STUB(ftKb_SpecialN_800F5AD8)
ABORT_STUB(ftKb_SpecialN_800F5B00)
ABORT_STUB(ftKb_SpecialN_800F5B10)
ABORT_STUB(ftKp_SpecialS_80132DD0)
ABORT_STUB(ftKp_SpecialS_80132DE0)
ABORT_STUB(ftKp_SpecialS_80132DF0)
ABORT_STUB(ftKp_SpecialS_80132E00)
ABORT_STUB(ftMh_CaptureDamageMasterHand_Anim)
ABORT_STUB(ftMh_CaptureDamageMasterHand_Coll)
ABORT_STUB(ftMh_CaptureDamageMasterHand_IASA)
ABORT_STUB(ftMh_CaptureDamageMasterHand_Phys)
ABORT_STUB(ftMh_CaptureMasterHand_Anim)
ABORT_STUB(ftMh_CaptureMasterHand_Coll)
ABORT_STUB(ftMh_CaptureMasterHand_IASA)
ABORT_STUB(ftMh_CaptureMasterHand_Phys)
ABORT_STUB(ftMh_CaptureWaitMasterHand_Anim)
ABORT_STUB(ftMh_CaptureWaitMasterHand_Coll)
ABORT_STUB(ftMh_CaptureWaitMasterHand_IASA)
ABORT_STUB(ftMh_CaptureWaitMasterHand_Phys)
ABORT_STUB(ftMh_ThrownMasterHand_Anim)
ABORT_STUB(ftMh_ThrownMasterHand_Coll)
ABORT_STUB(ftMh_ThrownMasterHand_IASA)
ABORT_STUB(ftMh_ThrownMasterHand_Phys)
ABORT_STUB(ftSb_Init_8014FBA4)
ABORT_STUB(ftYs_Shield_8012C1D4)
ABORT_STUB(ftYs_Shield_8012C49C)
ABORT_STUB(ftYs_Shield_8012C850)
ABORT_STUB(ftYs_SpecialN_8012CD40)
ABORT_STUB(ftYs_SpecialN_8012CD88)
ABORT_STUB(ftYs_SpecialN_GetExtAttr28)
ABORT_STUB(ftYs_SpecialN_GetExtAttr2C)
ABORT_STUB(ftYs_SpecialN_GetExtAttr34)
ABORT_STUB(ftYs_SpecialN_GetExtAttr38)
ABORT_STUB(grKongo_801D8270)
ABORT_STUB(grOldKongo_802105AC)
ABORT_STUB(it_80291CCC)
ABORT_STUB(it_80291CF4)
ABORT_STUB(it_80291FA8)
ABORT_STUB(it_80292E64)
ABORT_STUB(it_802944AC)
ABORT_STUB(it_802946B0)
ABORT_STUB(it_802947CC)
ABORT_STUB(it_80295F38)
ABORT_STUB(it_802EAE80)
