[build-system]
requires = ["setuptools", "wheel", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "melee-sim-light"
version = "0.0.0"
requires-python = ">=3.11"
dependencies = [
  "numpy",
]

[dependency-groups]
dev = [
  "peppi-py",
  "pyarrow",
  "py-ubjson",
  "pytest",
  "pytest-xdist",
  "setuptools",
  "zstandard",
]
