from __future__ import annotations

import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def _constants(source: str) -> dict[str, int]:
    return {
        name: int(value)
        for name, value in re.findall(r"export const ([A-Z0-9_]+) = (\d+);", source)
    }


def _characters(source: str) -> list[tuple[int, str]]:
    constants = _constants(source)
    match = re.search(r"SUPPORTED_CHARACTERS = Object\.freeze\(\[(.*?)\]\);", source, re.S)
    assert match is not None
    return [
        (constants[token] if token in constants else int(token), label)
        for token, label in re.findall(
            r'id:\s*([A-Z0-9_]+|\d+),\s*label:\s*"([^"]+)"', match.group(1)
        )
    ]


def _external_ids(source: str) -> dict[int, int]:
    return {
        int(internal): int(external)
        for internal, external in re.findall(
            r"if \(internalCharId === (\d+)\) return (\d+);", source
        )
    }


def test_live_viewer_supported_domain_and_assets() -> None:
    schema = (ROOT / "tools/viewer/live/schema.js").read_text()
    adapter = (ROOT / "tools/viewer/live/viewer_adapter.js").read_text()
    animation_cache = (
        ROOT / "tools/viewer/slippi-viewer/src/viewer/animationCache.ts"
    ).read_text()
    manifest = (ROOT / "tools/viewer/assets/character_zips.tsv").read_text()
    expected = {
        1: "Fox",
        2: "Captain Falcon",
        7: "Sheik",
        9: "Peach",
        15: "Jigglypuff",
        17: "Luigi", 0: "Mario", 21: "Dr. Mario", 10: "Ice Climbers",
        3: "Donkey Kong",
        25: "Ganondorf",
        12: "Pikachu", 13: "Samus",
        14: "Yoshi",
        18: "Marth",
        19: "Zelda",
        22: "Falco",
    }
    assert dict(_characters(schema)) == expected

    zip_match = re.search(
        r"characterZipUrlByExternalId = \[(.*?)\];", animation_cache, re.S
    )
    assert zip_match is not None
    zips = re.findall(r'"([^"]+\.zip)"', zip_match.group(1))
    packaged = {
        line.split("\t", 1)[0]
        for line in manifest.splitlines()
        if line and not line.startswith("#")
    }
    external = _external_ids(adapter)
    for internal_id in expected:
        filename = Path(zips[external.get(internal_id, internal_id)]).name
        assert filename in packaged


def test_generated_viewer_schema_is_current() -> None:
    generated = (ROOT / "tools/viewer/live/schema.generated.js").read_text()
    assert generated.startswith("// Generated by tools/viewer/schema.c; do not edit.")
