#include "runtime/wire.h"

#include <stddef.h>
#include <stdio.h>

#define VALUE(name, value)                                                    \
    printf("export const " name " = %zu;\n", (size_t) (value))
#define FIELD(type, field, name)                                              \
    printf("  " name ": %zu,\n", offsetof(type, field))

int main(void)
{
    puts("// Generated by tools/viewer/schema.c; do not edit.");
    VALUE("MATCH_CONFIG_SIZE", sizeof(MslCoreMatchConfig));
    VALUE("MATCH_CONFIG_PLAYER_SIZE", sizeof(MslCoreMatchPlayerConfig));
    VALUE("INPUT_SIZE", sizeof(MslCoreInput));
    VALUE("INPUT_PLAYER_SIZE", sizeof(MslCoreInputPlayer));
    VALUE("VIEWER_STATE_SIZE", sizeof(MslCoreViewerState));
    VALUE("VIEWER_PLAYER_SIZE", sizeof(MslCoreViewerPlayer));
    VALUE("VIEWER_HITBOX_SIZE", sizeof(MslCoreViewerHitbox));
    VALUE("ITEM_SIZE", sizeof(MslCoreItem));
    puts("");

    puts("export const matchConfigOffsets = Object.freeze({");
    FIELD(MslCoreMatchConfig, stage_id, "stageId");
    FIELD(MslCoreMatchConfig, frame_id, "frameId");
    FIELD(MslCoreMatchConfig, frame_pre_random_seed, "framePreRandomSeed");
    FIELD(MslCoreMatchConfig, initial_random_seed, "initialRandomSeed");
    FIELD(MslCoreMatchConfig, match_damage_ratio, "damageRatio");
    FIELD(MslCoreMatchConfig, num_players, "numPlayers");
    FIELD(MslCoreMatchConfig, is_teams, "isTeams");
    FIELD(MslCoreMatchConfig, friendly_fire, "friendlyFire");
    FIELD(MslCoreMatchConfig, stock_count, "stockCount");
    FIELD(MslCoreMatchConfig, camera_mode, "cameraMode");
    FIELD(MslCoreMatchConfig, online_fnmsubs_zero, "onlineFnmsubsZero");
    FIELD(MslCoreMatchConfig, brawl_offscreen_damage, "brawlOffscreenDamage");
    FIELD(MslCoreMatchConfig, freeze_dead_up_fall_physics,
          "freezeDeadUpFallPhysics");
    FIELD(MslCoreMatchConfig, ucf_cardinals_1_0_enabled,
          "ucfCardinals10Enabled");
    FIELD(MslCoreMatchConfig, ucf_shield_sdi_enabled, "ucfShieldSdiEnabled");
    FIELD(MslCoreMatchConfig, ucf_sdi_enabled, "ucfSdiEnabled");
    FIELD(MslCoreMatchConfig, stage_event_streams, "stageEventStreams");
    FIELD(MslCoreMatchConfig, players, "players");
    puts("});");

    puts("export const matchConfigPlayerOffsets = Object.freeze({");
    FIELD(MslCoreMatchPlayerConfig, char_id, "charId");
    FIELD(MslCoreMatchPlayerConfig, team_id, "teamId");
    FIELD(MslCoreMatchPlayerConfig, facing_and_port, "facingAndPort");
    FIELD(MslCoreMatchPlayerConfig, costume_id, "costumeId");
    FIELD(MslCoreMatchPlayerConfig, handicap, "handicap");
    puts("});");

    puts("export const inputPlayerOffsets = Object.freeze({");
    FIELD(MslCoreInputPlayer, buttons, "buttons");
    FIELD(MslCoreInputPlayer, main_x, "mainX");
    FIELD(MslCoreInputPlayer, main_y, "mainY");
    FIELD(MslCoreInputPlayer, c_x, "cX");
    FIELD(MslCoreInputPlayer, c_y, "cY");
    FIELD(MslCoreInputPlayer, l, "l");
    FIELD(MslCoreInputPlayer, r, "r");
    FIELD(MslCoreInputPlayer, nml_main_x, "nmlMainX");
    FIELD(MslCoreInputPlayer, nml_main_y, "nmlMainY");
    FIELD(MslCoreInputPlayer, nml_c_x, "nmlCX");
    FIELD(MslCoreInputPlayer, nml_c_y, "nmlCY");
    FIELD(MslCoreInputPlayer, nml_valid, "nmlValid");
    puts("});");

    puts("export const viewerOffsets = Object.freeze({");
    FIELD(MslCoreViewerState, frame_id, "frameId");
    FIELD(MslCoreViewerState, random_seed, "randomSeed");
    FIELD(MslCoreViewerState, stage_id, "stageId");
    FIELD(MslCoreViewerState, damage_ratio, "damageRatio");
    FIELD(MslCoreViewerState, num_players, "numPlayers");
    FIELD(MslCoreViewerState, is_teams, "isTeams");
    FIELD(MslCoreViewerState, friendly_fire, "friendlyFire");
    FIELD(MslCoreViewerState, terminal, "terminal");
    FIELD(MslCoreViewerState, stock_count, "stockCount");
    FIELD(MslCoreViewerState, players, "players");
    FIELD(MslCoreViewerState, items, "items");
    FIELD(MslCoreViewerState, stage, "stage");
    FIELD(MslCoreViewerState, camera, "camera");
    puts("});");

    puts("export const viewerPlayerOffsets = Object.freeze({");
    FIELD(MslCoreViewerPlayer, char_id, "charId");
    FIELD(MslCoreViewerPlayer, team_id, "teamId");
    FIELD(MslCoreViewerPlayer, facing, "facing");
    FIELD(MslCoreViewerPlayer, on_ground, "onGround");
    FIELD(MslCoreViewerPlayer, is_dead, "isDead");
    FIELD(MslCoreViewerPlayer, jumps_left, "jumpsLeft");
    FIELD(MslCoreViewerPlayer, stocks, "stocks");
    FIELD(MslCoreViewerPlayer, hurtbox_state, "hurtboxState");
    FIELD(MslCoreViewerPlayer, l_cancel, "lCancel");
    FIELD(MslCoreViewerPlayer, last_attack_landed, "lastAttackLanded");
    FIELD(MslCoreViewerPlayer, combo_count, "comboCount");
    FIELD(MslCoreViewerPlayer, last_hit_by, "lastHitBy");
    FIELD(MslCoreViewerPlayer, state_flags, "stateFlags");
    FIELD(MslCoreViewerPlayer, action_id, "actionId");
    FIELD(MslCoreViewerPlayer, action_frame, "actionFrame");
    FIELD(MslCoreViewerPlayer, hitlag, "hitlag");
    FIELD(MslCoreViewerPlayer, hitstun, "hitstun");
    FIELD(MslCoreViewerPlayer, ground_id, "groundId");
    FIELD(MslCoreViewerPlayer, animation_index, "animationIndex");
    FIELD(MslCoreViewerPlayer, pos_x, "posX");
    FIELD(MslCoreViewerPlayer, pos_y, "posY");
    FIELD(MslCoreViewerPlayer, speed_air_x_self, "speedAirXSelf");
    FIELD(MslCoreViewerPlayer, speed_ground_x_self, "speedGroundXSelf");
    FIELD(MslCoreViewerPlayer, speed_y_self, "speedYSelf");
    FIELD(MslCoreViewerPlayer, speed_x_attack, "speedXAttack");
    FIELD(MslCoreViewerPlayer, speed_y_attack, "speedYAttack");
    FIELD(MslCoreViewerPlayer, percent, "percent");
    FIELD(MslCoreViewerPlayer, shield_hp, "shieldHp");
    FIELD(MslCoreViewerPlayer, shield_x, "shieldX");
    FIELD(MslCoreViewerPlayer, shield_y, "shieldY");
    FIELD(MslCoreViewerPlayer, shield_z, "shieldZ");
    FIELD(MslCoreViewerPlayer, shield_radius, "shieldRadius");
    FIELD(MslCoreViewerPlayer, shield_tilt_x, "shieldTiltX");
    FIELD(MslCoreViewerPlayer, shield_tilt_y, "shieldTiltY");
    FIELD(MslCoreViewerPlayer, hitboxes, "hitboxes");
    puts("});");

    puts("export const viewerHitboxOffsets = Object.freeze({");
    FIELD(MslCoreViewerHitbox, x, "x");
    FIELD(MslCoreViewerHitbox, y, "y");
    FIELD(MslCoreViewerHitbox, z, "z");
    FIELD(MslCoreViewerHitbox, radius, "radius");
    FIELD(MslCoreViewerHitbox, damage, "damage");
    FIELD(MslCoreViewerHitbox, bone_part_id, "bonePartId");
    FIELD(MslCoreViewerHitbox, enabled, "enabled");
    puts("});");

    puts("export const itemOffsets = Object.freeze({");
    FIELD(MslCoreItem, exists, "exists");
    FIELD(MslCoreItem, state, "state");
    FIELD(MslCoreItem, type, "type");
    FIELD(MslCoreItem, owner, "owner");
    FIELD(MslCoreItem, instance_id, "instanceId");
    FIELD(MslCoreItem, attack_id, "attackId");
    FIELD(MslCoreItem, attack_instance, "attackInstance");
    FIELD(MslCoreItem, direction, "direction");
    FIELD(MslCoreItem, vel_x, "velX");
    FIELD(MslCoreItem, vel_y, "velY");
    FIELD(MslCoreItem, pos_x, "posX");
    FIELD(MslCoreItem, pos_y, "posY");
    FIELD(MslCoreItem, damage, "damage");
    FIELD(MslCoreItem, timer, "timer");
    FIELD(MslCoreItem, spawn_id, "spawnId");
    FIELD(MslCoreItem, misc0, "misc0");
    FIELD(MslCoreItem, misc1, "misc1");
    FIELD(MslCoreItem, misc2, "misc2");
    FIELD(MslCoreItem, misc3, "misc3");
    puts("});");

    puts("export const viewerStageOffsets = Object.freeze({");
    FIELD(MslCoreViewerStage, fod_platform_height, "fodHeight");
    FIELD(MslCoreViewerStage, fod_platform_valid, "fodValid");
    FIELD(MslCoreViewerStage, randall_exists, "randallExists");
    FIELD(MslCoreViewerStage, randall_x, "randallX");
    FIELD(MslCoreViewerStage, randall_y, "randallY");
    puts("});");

    puts("export const viewerCameraOffsets = Object.freeze({");
    FIELD(MslCoreViewerCamera, eye_x, "eyeX");
    FIELD(MslCoreViewerCamera, eye_y, "eyeY");
    FIELD(MslCoreViewerCamera, eye_z, "eyeZ");
    FIELD(MslCoreViewerCamera, interest_x, "interestX");
    FIELD(MslCoreViewerCamera, interest_y, "interestY");
    FIELD(MslCoreViewerCamera, interest_z, "interestZ");
    FIELD(MslCoreViewerCamera, fov, "fov");
    puts("});");
    return 0;
}
