#ifndef MSL_PREPROCESS_NATIVE_H
#define MSL_PREPROCESS_NATIVE_H

#include "msl_binding_internal.h"

PyObject* msl_derive_combo_seed_fields_py(PyObject* self, PyObject* args);
PyObject* msl_derive_instance_id_x2073_py(PyObject* self, PyObject* args);
PyObject* msl_derive_instance_id_counter_py(PyObject* self, PyObject* args);
PyObject* msl_derive_item_spawn_id_counter_py(PyObject* self, PyObject* args);
PyObject* msl_derive_staling_history_py(PyObject* self, PyObject* args);
PyObject* msl_process_stick_i8_units_py(PyObject* self, PyObject* args);
PyObject* msl_derive_ucf_pad_buffer_state_py(PyObject* self, PyObject* args);
PyObject* msl_compute_tilt_timer_axis_py(PyObject* self, PyObject* args);
PyObject* msl_compute_tilt_timer_axis_pre_post_py(PyObject* self, PyObject* args);
PyObject* msl_compute_tilt_timer_y_pre_post_with_fall_fast_py(PyObject* self, PyObject* args);
PyObject* msl_derive_grab_mash_stick_sign_post_py(PyObject* self, PyObject* args);
PyObject* msl_derive_guard_release_lockout_and_lightshield_py(PyObject* self, PyObject* args);
PyObject* msl_derive_damage_hitlag_sdi_reset_post_mask_py(PyObject* self, PyObject* args);
PyObject* msl_derive_damage_entry_tilt_timer_reset_post_mask_py(PyObject* self, PyObject* args);
PyObject* msl_derive_guard_reflect_timer_plus1_py(PyObject* self, PyObject* args);
PyObject* msl_derive_guard_reflect_origin_guardon_py(PyObject* self, PyObject* args);
PyObject* msl_derive_guard_special_enable_timer_x1c_py(PyObject* self, PyObject* args);
PyObject* msl_derive_guard_setoff_hitlag_damage_min_py(PyObject* self, PyObject* args);
PyObject* msl_derive_guard_setoff_hitlag_exit_phase_py(PyObject* self, PyObject* args);
PyObject* msl_derive_guard_setoff_post_hitlag_owner_py(PyObject* self, PyObject* args);
PyObject* msl_derive_run_x0_py(PyObject* self, PyObject* args);
PyObject* msl_derive_runbrake_cmd0_py(PyObject* self, PyObject* args);
PyObject* msl_derive_dash_x4_py(PyObject* self, PyObject* args);
PyObject* msl_derive_ecb_lock_timer_py(PyObject* self, PyObject* args);
PyObject* msl_derive_ecb_lock_bottom_rel_y_py(PyObject* self, PyObject* args);
PyObject* msl_derive_damage_hitlag_colldata_ecb_py(PyObject* self, PyObject* args);
PyObject* msl_compute_press_timer_u8_py(PyObject* self, PyObject* args);
PyObject* msl_compute_lr_press_timer_x67f_py(PyObject* self, PyObject* args);
PyObject* msl_derive_turn_internals_py(PyObject* self, PyObject* args);
PyObject* msl_compute_x672_trigger_timer_pre_post_py(PyObject* self, PyObject* args);
PyObject* msl_derive_downwait_timer_py(PyObject* self, PyObject* args);
PyObject* msl_derive_damage_jump_buffer_x14_py(PyObject* self, PyObject* args);
PyObject* msl_derive_damage_meteor_cancel_x1a_py(PyObject* self, PyObject* args);
PyObject* msl_derive_damage_post_hitlag_cb_kind_py(PyObject* self, PyObject* args);
PyObject* msl_derive_guard_tilt_state_py(PyObject* self, PyObject* args);
PyObject* msl_derive_shine_release_state_py(PyObject* self, PyObject* args);
PyObject* msl_derive_kneebend_internals_py(PyObject* self, PyObject* args);
PyObject* msl_derive_smash_charge_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_magnify_damage_counter_x1910_py(PyObject* self, PyObject* args);
PyObject* msl_derive_colanim_internals_py(PyObject* self, PyObject* args);
PyObject* msl_derive_capture_mash_buttons_pressed_py(PyObject* self, PyObject* args);
PyObject* msl_derive_capture_grab_hidden_post_py(PyObject* self, PyObject* args);
PyObject* msl_derive_ledge_cooldown_py(PyObject* self, PyObject* args);
PyObject* msl_derive_cliff_ledge_floor_segment_id_py(PyObject* self, PyObject* args);
PyObject* msl_derive_cliff_option_stick_latch_x8_py(PyObject* self, PyObject* args);
PyObject* msl_derive_match_flow_timer_py(PyObject* self, PyObject* args);
PyObject* msl_derive_passivewall_timer_py(PyObject* self, PyObject* args);
PyObject* msl_derive_walljump_phase_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_entry_end_fall_lock_py(PyObject* self, PyObject* args);
PyObject* msl_derive_jab_rapid_count_py(PyObject* self, PyObject* args);
PyObject* msl_derive_walk_anim_source_vel_py(PyObject* self, PyObject* args);
PyObject* msl_derive_walk_retarget_tick_source_vel_py(PyObject* self, PyObject* args);
PyObject* msl_derive_run_anim_source_vel_py(PyObject* self, PyObject* args);
PyObject* msl_derive_facing_dir1_sign_py(PyObject* self, PyObject* args);
PyObject* msl_derive_common_fall_blend_seed_py(PyObject* self, PyObject* args);
PyObject* msl_derive_sheik_needle_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_sheik_chain_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_sheik_vanish_floor_skip_segments_py(PyObject* self, PyObject* args);
PyObject* msl_derive_camera_target_world_py(PyObject* self, PyObject* args);
PyObject* msl_derive_hitbox_prev_centers_py(PyObject* self, PyObject* args);
PyObject* msl_derive_combo_push_timer_seed_py(PyObject* self, PyObject* args);
PyObject* msl_compute_fighter_stick_input_counters_py(PyObject* self, PyObject* args);
PyObject* msl_compute_fighter_trigger_input_counters_py(PyObject* self, PyObject* args);
PyObject* msl_compute_fighter_button_timers_py(PyObject* self, PyObject* args);
PyObject* msl_derive_illusion_ghost_pos012_py(PyObject* self, PyObject* args);
PyObject* msl_derive_combat_hitlist_seed_fields_py(PyObject* self, PyObject* args);
PyObject* msl_derive_specialhi_rotate_model_seed_lane_py(PyObject* self, PyObject* args);
PyObject* msl_derive_throw_pulse_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_throw_laser_item_hitlist_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_item_attack_fields_py(PyObject* self, PyObject* args);
PyObject* msl_derive_item_reflect_damage_mul_py(PyObject* self, PyObject* args);
PyObject* msl_derive_item_hidden_callback_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_yoshi_shyguy_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_dream_whispy_wind_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_illusion_seed_position_updates_py(PyObject* self, PyObject* args);
PyObject* msl_trim_stale_hitlist_seed_bridge_py(PyObject* self, PyObject* args);
PyObject* msl_derive_attacker_shield_ground_kb_vel_py(PyObject* self, PyObject* args);
PyObject* msl_derive_guardsetoff_frame_speed_overrides_py(PyObject* self, PyObject* args);
PyObject* msl_derive_shield_contact_seed_bridge_py(PyObject* self, PyObject* args);
PyObject* msl_derive_rebound_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_mpcoll_wall_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_source_clear_timer_py(PyObject* self, PyObject* args);
PyObject* msl_derive_source_clear_grounded_damage_clear_phase_py(PyObject* self, PyObject* args);
PyObject* msl_derive_source_clear_terminal_phase_py(PyObject* self, PyObject* args);
PyObject* msl_derive_fighter_8006cda4_pre_gate_count_py(PyObject* self, PyObject* args);
PyObject* msl_derive_source_clear_processhit_damage_pending_phase_py(PyObject* self,
                                                                     PyObject* args);
PyObject* msl_derive_phantom_damage_pending_seed_lanes_py(PyObject* self, PyObject* args);
PyObject* msl_derive_grounded_overlap_hidden_pos_z_py(PyObject* self, PyObject* args);

#endif
